<a href="https://colab.research.google.com/github/kamilnoczynski/data_science/blob/main/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [6]:
v1 = np.array([-1,4])

In [3]:
v1

array([0, 4])

In [7]:
np.linalg.norm(v1)

4.123105625617661

In [11]:
X = np.array([[2,-1,3],
             [3,1,0]])
Y = np.array([[2,1,-1],
             [0,-1,2],
             [3,2,0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [12]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])