<a href="https://colab.research.google.com/github/kamilnoczynski/data_science/blob/main/numpy%5Cnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
np.__version__

'1.19.5'

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3,2.4,3.5])
print(x)

[1.3 2.4 3.5]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.shape

(2, 3)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A = np.array([4,3,2,1])
B = np.array([8, 7, -1, 2])
print(A)
print(B)

[4 3 2 1]
[ 8  7 -1  2]


In [ ]:
A + B

array([12, 10,  1,  3])

In [ ]:
A - B

array([-4, -4,  3, -1])

In [ ]:
A + 3

array([7, 6, 5, 4])

In [ ]:
np.add(A,B)

array([12, 10,  1,  3])

In [ ]:
np.subtract(A,B)

array([-4, -4,  3, -1])

In [ ]:
np.random.randn(10)

array([ 0.44429543,  1.56840886,  0.18734242, -0.05126066, -1.00678024,
        1.66174731,  0.43973039,  0.27018012,  1.43050869,  0.70781437])

In [ ]:
np.random.randn(10,4)

array([[ 2.30456161, -1.48037329, -0.56245001, -2.51504621],
       [ 1.34552206,  0.29218732,  0.09982178, -0.02317409],
       [ 1.27269524, -0.22023188,  1.31073404, -0.48188061],
       [ 0.21922729, -0.82500387,  1.22708756, -0.64475504],
       [ 1.73294311, -0.01443098,  0.28068165,  0.33199221],
       [-0.7733866 , -2.05826021,  1.20819067, -1.89991002],
       [ 2.14167429, -0.04297955, -0.24919566,  1.3805394 ],
       [ 0.03417674,  2.70512339, -0.34935366, -0.62710048],
       [ 0.63020774,  0.10692987,  0.99967407,  1.2936371 ],
       [-0.39851007, -0.56063449, -1.99285103, -0.69722505]])

In [ ]:
np.random.rand()

0.8131027734319185

In [1]:
bool(1.3)

True

In [6]:
np.all([1,2,3])

True

In [9]:
A = np.random.rand(5)
A

array([0.36011373, 0.8610088 , 0.3926285 , 0.41054278, 0.60941861])

In [10]:
np.argmax(A)

1

In [11]:
A[np.argmax(A)]

0.8610087980146682

In [12]:
np.argsort(A)

array([0, 2, 3, 4, 1])

In [13]:
np.mean(A)

0.5267424838694359

In [15]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
A[2]

2

In [17]:
A[:2]

array([0, 1])

In [20]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [21]:
A[-1]

19

In [22]:
A[10:15]

array([10, 11, 12, 13, 14])

In [23]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
A[1]

array([5, 6, 7, 8, 9])

In [25]:
A[:,1]

array([ 1,  6, 11, 16])

In [26]:
A[1:2,1:4]

array([[6, 7, 8]])

In [27]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [29]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [30]:
A.shape

(4, 5)

In [31]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])